#!/bin/sh

RETVAL=0
service=/usr/local/bin/ruby_cue/cue_start.sh
process_name=$(basename $service)
lockfile="/var/lock/subsys/${process_name}"
pidfile="/var/run/${process_name}.pid"

. /etc/init.d/functions

start() {
  echo "starting ruby_cue..."
  daemon $service $pidfile
  RETVAL=$?
  [ $RETVAL = 0 ] && touch $lockfile
  return $RETVAL
}

stop() {
  echo "stopping ruby_cue..."
  killproc -p $pidfile $service
  RETVAL=$?
  [ $RETVAL = 0 ] && rm -f $lockfile $pidfile
  return $RETVAL
}

rh_status() {
  status -p ${pidfile} $service
  RETVAL=$?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    rh_status
    ;;
  *)
     echo "Usage: $0 {start|stop|status}"
     exit 1
esac
exit $RETVAL
