#!/bin/sh

service=/usr/local/bin/ruby_cue/cue_start.sh
pidfile=/tmp/rubycue.pid

. /etc/init.d/functions

case "$1" in
  start)
#     $service $pidfile
#     RETVAL=$?
     daemon $service
     echo "Started service"
     ;;
  stop)
     kill `cat $pidfile`
#     RETVAL=$?
#     rm -f $pidfile
     killproc $service
     echo "Stopped service"
     ;;
  status)
     status -p ${pidfile} $service
     RETVAL=$?
     ;;
  *)
     echo "Usage: $0 {start|stop|status}"
     exit 1
esac
exit $RETVAL
