#!/bin/sh

service=/root/cue_daemon.rb
pidfile=/root/rubycue.pid

case "$1" in
  start)
     $service $pidfile
     RETVAL=$?
     echo "Started service"
     ;;
  stop)
     kill `cat $pidfile`
     RETVAL=$?
     rm -f $pidfile
     echo "Stopped service"
     ;;
  status)
     status -p ${pidfile} $service
     RETVAL=$?
     ;;
  *)
     echo "Usage: $0 {start|stop|status}"
     exit 1
esac
exit $RETVAL
